Imports System.IO
Imports System.Text.RegularExpressions
Public Class New_Conf
    Public Sub New()
        Directory.CreateDirectory(Main.change_Desktop_Path & "DesktopSpace_Theme/")
        Using Writer As New StreamWriter(Main.change_Desktop_Path & "DesktopSpace.conf")
            Writer.WriteLine(Main.change_Desktop_Path & "DesktopSpace_Theme/Default_Theme.txt")
        End Using
        Using Writer As New StreamWriter(Main.change_Desktop_Path & "DesktopSpace_Theme/Default_Theme.txt")
            Writer.WriteLine("这是DesktopSpace的默认主题")
            Writer.WriteLine("主题内容从""Theme_Start""开始,由""Theme_End""结束。从""Theme_Start""开始,前9行为:")
            Writer.WriteLine("主窗口颜色")
            Writer.WriteLine("Box的大小:两个数字表示，中间由逗号隔开。有多少个桌面就会生成多少个Box,但不会超过10个。")
            Writer.WriteLine("Box和主窗体左边界的距离：用一个数字表示")
            Writer.WriteLine("Box和主窗体上边界的距离：用一个数字表示")
            Writer.WriteLine("Box之间的距离：用一个数字表示")
            Writer.WriteLine("标题的字体名称：输入一个字体名称，例如“"微软雅黑"”，无需带引号。")
            Writer.WriteLine("标题的字体字号：一个数字，可以是小数")
            Writer.WriteLine("标题文字颜色：3位整数表示RGB颜色，用逗号隔开，例如”“255，255，255”“。")
            Writer.WriteLine("文字底部标识线的高度：一个数字表示")
            Writer.WriteLine("文字底部标识线被选中的颜色：3位整数表示")
            Writer.WriteLine("文字底部标识线鼠标经过时的颜色：3位整数表示。从这一行开始，便是对单个Box的设置。")
            Writer.WriteLine("标题名称：任意可以被用来创建文件夹的字符。")
            Writer.WriteLine("图标路径：图片的完整路径,也可以是一个图片的链接")
            Writer.WriteLine("图标位置：图标在Box上的偏移量")
            Writer.WriteLine("图标大小：图标显示的大小。4行为一组，可以继续往下设置第二个Box（桌面）。")
            Writer.WriteLine("标题名称2")
            Writer.WriteLine("图标路径2")
            Writer.WriteLine("图标位置2")
            Writer.WriteLine("图标大小2")
            Writer.WriteLine("标题名称3")
            Writer.WriteLine("图标路径3")
            Writer.WriteLine("图标位置3")
            Writer.WriteLine("图标大小3")
            Writer.WriteLine("下面开始是可以被程序识别的内容")
            Writer.WriteLine("Theme_Start")
            Writer.WriteLine("98,98,98")
            Writer.WriteLine("130,150")
            Writer.WriteLine("50")
            Writer.WriteLine("40")
            Writer.WriteLine("20")
            Writer.WriteLine("幼圆")
            Writer.WriteLine("16.2")
            Writer.WriteLine("255,255,255")
            Writer.WriteLine("9")
            Writer.WriteLine("0,255,0")
            Writer.WriteLine("255,215,0")
            Writer.WriteLine("Default")
            Writer.WriteLine("D:/test.jpg")
            Writer.WriteLine("0,0")
            Writer.WriteLine("200,200")
            Writer.WriteLine("Game")
            Writer.WriteLine("D:/test.jpg")
            Writer.WriteLine("0,0")
            Writer.WriteLine("200,200")
            Writer.WriteLine("Music")
            Writer.WriteLine("D:/test.jpg")
            Writer.WriteLine("0,0")
            Writer.WriteLine("200,200")
            Writer.WriteLine("Code")
            Writer.WriteLine("D:/test.jpg")
            Writer.WriteLine("0,0")
            Writer.WriteLine("200,200")
            Writer.WriteLine("Theme_End")
        End Using

    End Sub

End Class
